---
title: "writing_functions"
author: "Tianshu Liu"
date: "2022-10-27"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


function_name = function(argument){

  function body
  
}

Z-score
```{r}
x_vec = rnorm(25, mean = 7, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

# function
z_scores = function(x){
  if(!is.numeric(x)){
    stop("Z scores only work for numbers")
  }else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  z = (x - mean(x)) / sd(x)
  z     # return value
}

z_scores(x_vec)
z_scores(x = 1:10)
z_scores(x = rbinom(100, 1, 0.6))
```

Multiple outputs

```{r}
mean_and_sd = function(x){
  
  if(!is.numeric(x)){
    stop("Z scores only work for numbers")
  }else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}

mean_and_sd(x = x_vec)
mean_and_sd(x = 1:10)
mean_and_sd(x = rbinom(100, 1, .5))
```

```{r}
x_vec = rnorm(n = 25000, mean = 17, sd = 4)
tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

```{r}
sim_mean_sd = function(n_obs, true_mean, true_sd){
  
  x = rnorm(n_obs, mean = true_mean, sd = true_sd)
  
  tibble(
    mean = mean(x),
    sd = sd(x)
  )
}

sim_mean_sd(n_obs = 25000, true_mean = 10, true_sd = 5)
sim_mean_sd(25000, 10, 5)
```


```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

Use function to get reviews

```{r}
read_page_reviews = function(url){
  dynamite_html = read_html(url)
  
  review_titles = 
    dynamite_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()

  review_stars = 
    dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()

  review_text = 
    dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)

  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  
  reviews
}

url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

read_page_reviews(url = url)

base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_url = str_c(base_url, c(1, 2, 3, 4, 5))

dynamic_reviews = 
  bind_rows(
    read_page_reviews(vec_url[1]),
    read_page_reviews(vec_url[2]),
    read_page_reviews(vec_url[3]),
    read_page_reviews(vec_url[4]),
    read_page_reviews(vec_url[5])
  )

dynamic_reviews %>% view()
```



